### ISSUE TITLE
Support for geopandas >=1.0.0

### ISSUE THREAD

**Issue by amillb** [cenpy-devs/cenpy#163]
`geopandas` 1.0.0 removed the [previously deprecated](https://geopandas.org/en/stable/docs/changelog.html#version-0-10-0-october-3-2021) parameter `op` parameter in `sjoin`.  Rather than `op`, `predicate` should now be used. 

This means that `from_county()` in `cenpy` now throws an error.  For example:

`products.ACS(2017).from_county('Riverside, CA', level='tract', variables='B25035_001E')`

> TypeError: sjoin() got an unexpected keyword argument 'op'

I think this is simple to fix through replacing `op=` with `predicate=` in `cenpy.products()`.

**Comment by knaaptime** [comment]
hey, thanks for this. Apologies, the team is spread extremely thin and hasn't had much time for maintenance in awhile. You're right, that should probably do it. If you're up for a PR we can get it merged. 

we also need to migrate the tests over to github actions to get things running again

**Comment by qthequartermasterman** [comment]
I was going to open a PR to fix it, but it looks like it is already fixed. This looks like it was resolved by @ljwolf in https://github.com/cenpy-devs/cenpy/commit/88c9ae19d328c0dfccff8fdd015f46aedc9b313d, but it does not look like it was in the last release to PyPI.

**Comment by ZacharyST** [comment]
Was this changer pushed to PyPI?  I just pip install-ed cenpy but still get this error.
